### ISSUE TITLE
CB-12236 - Checklist to fix plugin RELEASENOTES

### ISSUE THREAD

**Issue by shazron** [cordova/cordova-status#3]
See https://issues.apache.org/jira/browse/CB-12236 (master)

- [x] cordova-plugin-battery-status 
- [x] cordova-plugin-camera 
- [x] cordova-plugin-console 
- [x] cordova-plugin-contacts 
- [x] cordova-plugin-device 
- [x] cordova-plugin-device-motion 
- [x] cordova-plugin-device-orientation 
- [x] cordova-plugin-dialogs 
- [x] cordova-plugin-file 
- [x] cordova-plugin-file-transfer 
- [x] cordova-plugin-geolocation 
- [x] cordova-plugin-globalization 
- [x] cordova-plugin-inappbrowser 
- [x] cordova-plugin-legacy-whitelist 
- [x] cordova-plugin-media 
- [x] cordova-plugin-media-capture 
- [x] cordova-plugin-network-information 
- [x] cordova-plugin-screen-orientation 
- [x] cordova-plugin-splashscreen 
- [x] cordova-plugin-statusbar 
- [x] cordova-plugin-test-framework 
- [x] cordova-plugin-vibration 
- [x] cordova-plugin-whitelist 
- [x] cordova-plugin-wkwebview-engine

Update RELEASENOTES.md in the release branches (manual cherry-pick from master)

- [x] cordova-plugin-battery-status 
- [x] cordova-plugin-camera 
- [x] cordova-plugin-console 
- [x] cordova-plugin-contacts 
- [x] cordova-plugin-device 
- [x] cordova-plugin-device-motion 
- [x] cordova-plugin-device-orientation 
- [x] cordova-plugin-dialogs 
- [x] cordova-plugin-file 
- [x] cordova-plugin-file-transfer 
- [x] cordova-plugin-geolocation 
- [x] cordova-plugin-globalization 
- [x] cordova-plugin-inappbrowser 
- [x] cordova-plugin-legacy-whitelist 
- [x] cordova-plugin-media 
- [x] cordova-plugin-media-capture 
- [x] cordova-plugin-network-information 
- [x] cordova-plugin-screen-orientation 
- [x] cordova-plugin-splashscreen 
- [x] cordova-plugin-statusbar 
- [x] cordova-plugin-test-framework 
- [x] cordova-plugin-vibration 
- [x] cordova-plugin-whitelist 
- [x] cordova-plugin-wkwebview-engine

npm publish

- [x] cordova-plugin-battery-status 
- [x] cordova-plugin-camera 
- [x] cordova-plugin-console 
- [x] cordova-plugin-contacts 
- [x] cordova-plugin-device 
- [x] cordova-plugin-device-motion 
- [x] cordova-plugin-device-orientation 
- [x] cordova-plugin-dialogs 
- [x] cordova-plugin-file 
- [x] cordova-plugin-file-transfer 
- [x] cordova-plugin-geolocation 
- [x] cordova-plugin-globalization 
- [x] cordova-plugin-legacy-whitelist 
- [x] cordova-plugin-media 
- [x] cordova-plugin-media-capture 
- [x] cordova-plugin-network-information 
- ~[ ] cordova-plugin-screen-orientation (moved to later release)~
- [x] cordova-plugin-splashscreen 
- [x] cordova-plugin-statusbar 
- [x] cordova-plugin-test-framework 
- [x] cordova-plugin-vibration 
- [x] cordova-plugin-whitelist 
- [x] cordova-plugin-wkwebview-engine

**Comment by shazron** [comment]
Update RELEASENOTES.md in the release branches (manual cherry-pick from master)

- [ ] cordova-plugin-battery-status 
- [ ] cordova-plugin-camera 
- [ ] cordova-plugin-console 
- [ ] cordova-plugin-contacts 
- [ ] cordova-plugin-device 
- [ ] cordova-plugin-device-motion 
- [ ] cordova-plugin-device-orientation 
- [ ] cordova-plugin-dialogs 
- [ ] cordova-plugin-file 
- [ ] cordova-plugin-file-transfer 
- [ ] cordova-plugin-geolocation 
- [ ] cordova-plugin-globalization 
- [ ] cordova-plugin-inappbrowser 
- [ ] cordova-plugin-legacy-whitelist 
- [ ] cordova-plugin-media 
- [ ] cordova-plugin-media-capture 
- [ ] cordova-plugin-network-information 
- [ ] cordova-plugin-screen-orientation 
- [ ] cordova-plugin-splashscreen 
- [ ] cordova-plugin-statusbar 
- [ ] cordova-plugin-test-framework 
- [ ] cordova-plugin-vibration 
- [ ] cordova-plugin-whitelist 
- [ ] cordova-plugin-wkwebview-engine

**Comment by shazron** [comment]
Completed.
